[package]
name = "upup_server"
description = "The server parth of UpUp"
version = "0.0.1"
authors = [
    "Alexander Galaydyuk <galaydyukav@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
